# -*- coding: utf-8 -*-
"""01.monte_carlo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10U4XNS46U0QXFk_VB7mwpUmTpqT9nBlh
"""

import random
import math
import matplotlib.pyplot as plt

n=[100, 1000, 5000, 10000]
PI_valueArray = []
area_circle = []

miss_theta = []
miss_D = []
hit_theta = []
hit_D = []

for trials in n:
  hits=0
  for i in range(trials):
     x= random.uniform(-5,5)
     y= random.uniform(-5,5)
     if math.sqrt(x**2+y**2)<=3:
       hits=hits+1
       hit_theta.append(x)
       hit_D.append(y)
     else:
       miss_theta.append(x)
       miss_D.append(y)   


  PI= (100/9)* (hits/trials)
  PI_valueArray.append(PI)
  A= 100* (hits/trials)
  area_circle.append(A)
  

  print(f"For trial : {trials}")
  print(f"Value of PI: {PI}")
  print(f"Area of circle: {A}")
  print("Scatter Plot :")
  plt.scatter(hit_theta,hit_D,c='red', label="Hit points")
  plt.scatter(miss_theta,miss_D,c='green', label="Miss points")
  plt.show()


x1=["100","1000","5000","10000"]
print(PI_valueArray)
plt.bar(x1,PI_valueArray,color="green")
plt.ylabel("PI values")
plt.xlabel("Values of N")
plt.show()
print(area_circle)
plt.bar(x1,area_circle,color="green")
plt.ylabel("Area values")
plt.xlabel("Values of N")
plt.show()