# -*- coding: utf-8 -*-
"""03. monte_carlo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jp-bFURYbkT9OfFFMG3X8V1EE1dVSSIv
"""

import random
import math
import matplotlib.pyplot as plt

n=[100, 1000, 5000, 10000]

area_triangle = []

miss_theta = []
miss_D = []
hit_theta = []
hit_D = []

for trials in n:
  hits=0
  for i in range(trials):
     x= random.uniform(0,8)
     y= random.uniform(0,4)
     
     if x>=0 and x<=4:
            if y**2<=4*x:
              hits=hits+1
              hit_theta.append(x)
              hit_D.append(y)
            else:
               miss_theta.append(x)
               miss_D.append(y)

     else:
       if y<= 8- x:
         hits=hits+1
         hit_theta.append(x)
         hit_D.append(y)

       else:
         miss_theta.append(x)
         miss_D.append(y)


  



  A= 32* (hits/trials)
  area_triangle.append(A)
  

  print(f"For trial : {trials}")

  print(f"Area of shaded part: {A}")
  print("Scatter Plot :")
  plt.scatter(hit_theta,hit_D,c='red', label="hit points")
  plt.scatter(miss_theta,miss_D,c='green', label="miss points")
  plt.legend()
  plt.show()