# -*- coding: utf-8 -*-
"""Buffon's_011171018.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1svPoeAU1Qjmlp6oPZD1TV-jPszfINkIB
"""

import random
import math
import matplotlib.pyplot as plt


hit = 0
n = 1000
miss_theta = []
miss_D = []
hit_theta = []
hit_D = []

d = int(input())
l = int(input())

for i in range(n):
  D = random.uniform(0,d/2)
  theta = random.uniform(0,math.pi)
  if D <= l/2 * math.sin(theta):
    hit = hit+1
    hit_theta.append(theta)
    hit_D.append(D)
  else:
    miss_theta.append(theta)
    miss_D.append(D)

res = (2*l/d)*(n_trials/hit)
print(res)

plt.scatter(hit_theta,hit_D,c='red', label="Hit points")
plt.scatter(miss_theta,miss_D,c='green', label="Miss points")
plt.xlabel("Theta")
plt.ylabel("D")
plt.legend()