# -*- coding: utf-8 -*-
"""Serial_chase.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-b8XnPOjvcbD9nv2hijiAlcjt4MNX0Fg
"""

import math
import matplotlib.pyplot as plt

def dis(x1,y1,x2,y2):
  return math.sqrt((x1-x2)**2 + (y1-y2)**2)


x_A=[10]
y_A=[0]
x_B=[0]
y_B=[10]
x_C=[10]
y_C=[10]
x_D=[0]
y_D=[0]

v_A=3
v_B=5
v_C=7
v_D=2

c_got_shoot=0
b_got_shoot=0
d_got_shoot=0

distCB= dis(x_C[0],y_C[0],x_B[0],y_B[0])
distBD= dis(x_B[0],y_B[0],x_D[0],y_D[0])
distDA= dis(x_D[0],y_D[0],x_A[0],y_A[0])

for t in range(1,20):
  #C is chased by B Target- C 
  sin = (y_C[t-1] - y_B[t-1]) / distCB
  cos= (x_C[t-1] - x_B[t-1]) / distCB
  new_x_B= x_B[t-1]+ v_B* cos
  new_y_B= y_B[t-1] + v_B*sin
  x_B.append(new_x_B)
  y_B.append(new_y_B)

  #B is chased by D target-B 
  sin = (y_B[t-1] - y_D[t-1]) / distBD
  cos= (x_B[t-1] - x_D[t-1]) / distBD
  new_x_D= x_D[t-1]+ v_D* cos
  new_y_D= y_D[t-1] + v_D*sin
  x_D.append(new_x_D)
  y_D.append(new_y_D)

  #D is chased by A target-D 
  sin = (y_D[t-1] - y_A[t-1]) / distDA
  cos= (x_D[t-1] - x_A[t-1]) / distDA
  new_x_A= x_A[t-1]+ v_A* cos
  new_y_A= y_A[t-1] + v_A*sin
  x_A.append(new_x_A)
  y_A.append(new_y_A)

  new_x_C= x_C[t-1]
  new_y_C= y_C[t-1]+v_C
  x_C.append(new_x_C)
  y_C.append(new_y_C)

  distCB= dis(x_C[t],y_C[t],x_B[t],y_B[t])
  distBD= dis(x_B[t],y_B[t],x_D[t],y_D[t])
  distDA= dis(x_D[t],y_D[t],x_A[t],y_A[t])

  print("At time :",t)
  print("Car A is at :[",new_x_A,", ",new_y_A,"]")
  print("Car B is at :[",new_x_B,", ",new_y_B,"]")
  print("Car C is at :[",new_x_C,", ",new_y_C,"]")
  print("Car D is at :[",new_x_D,", ",new_y_D,"]")
  

  if distCB<5:
    c_got_shoot = c_got_shoot+1
    print("B shoots C, Distance =",distCB)

  if distBD<5:
    b_got_shoot = b_got_shoot+1
    print("D shoots B, Distance =",distBD)

  if distDA<5:
    d_got_shoot = d_got_shoot+1
    print("A shoots D, Distance =",distDA)

  else:
    print("NO ONE SHOOTS!!")

  print(" ")

print("D got shoot ",d_got_shoot,"times")
print("C got shoot ",c_got_shoot,"times")
print("B got shoot ",b_got_shoot,"times")

list1=['A', 'B', 'C', 'D']
plt.plot(x_A,y_A)
plt.plot(x_B,y_B)
plt.plot(x_C,y_C)
plt.plot(x_D,y_D)

#plt.ylim(0,11) 
#plt.xlim(0,150) 
plt.ylabel('Y-Axis')
plt.xlabel('X-Axis')
plt.legend(list1,loc='upper left')
plt.show()