# -*- coding: utf-8 -*-
"""Problem-1_deadAlive.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KTqVo_n6P8k3jx5M9AV6QOW_3xa9WDc6
"""

N = 5

arr = [[0, 1, 0, 0, 0], 
    [0, 0, 1, 0, 0], 
    [0, 1, 1, 0, 1], 
    [0, 1, 0, 0, 1],
    [0, 0, 0, 0, 0]] 
  
print("time- 0")
  
for i in range(5):
    for j in range(5):
      print(arr[i][j], end=" ")
    print('')
Time = 20
b = [[0 for x in range(N)] 
      for y in range(N)] 

l = 0
t = 0

while (Time):
		
		for i in range(N) : 
			for j in range(N): 
				l = 0

				if (i > 0 and arr[i - 1][j] == 1): 
					l += 1
				if (j > 0 and arr[i][j - 1] == 1): 
					l += 1
				if (i > 0 and j > 0 and arr[i - 1][j - 1] == 1): 
					l += 1
				if (i < N - 1 and arr[i + 1][j] == 1): 
					l += 1
				if (j < N - 1 and arr[i][j + 1] == 1): 
					l += 1
				if (i < N - 1 and j < N - 1 and arr[i + 1][j + 1] == 1): 
					l += 1
				if (i < N - 1 and j > 0 and arr[i + 1][j - 1] == 1): 
					l += 1
				if (i > 0 and j < N - 1 and arr[i - 1][j + 1] == 1): 
					l += 1


				if (arr[i][j] == 1) : 
					if (l >= 2 and l <= 3): 
						b[i][j] = 1
					elif (l < 2): 
						b[i][j] = 0
					elif (l > 3):
						b[i][j] = 0
					else:
						b[i][j] = 1

				if (arr[i][j] == 0): 
					if (l == 3): 
						b[i][j] = 1
					else: 
						b[i][j] = 0				
		Time = Time -1
		t += 1
		for k in range(N): 
			for m in range( N): 
				arr[k][m] = b[k][m]
		print()
		print("time- ",t)
		print()
		for i in range(N):
			for j in range(N):
				print(arr[i][j], end = " ")
			print()