# -*- coding: utf-8 -*-
"""Problem-2_Congruential_Generators.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZlTaEyIJJvTbT5aqYcye-u8S7gqg-Dtp
"""

import math
import random
import matplotlib.pyplot as plt

t = [100,1000,5000] 

for n in t:
  z1=[12, 7]
  z2=[3, 5]
  z3=[2, 7]
  u=[]

  u1=[0.75,0.4375]
  for i in range(2,n+1):
    new_z1= (13*z1[i-1]+11*z1[i-2]+3)%16
    z1.append(new_z1)
    new_u1=new_z1/16
    u1.append(new_u1)

  u2=[0.17647058823,0.29411765]
  for i in range(2,n+1):
    new_z2=(12*(z2[i-1]**2)+13*z2[i-2])%17
    z2.append(new_z2)
    new_u2=new_z2/17
    u2.append(new_u2)

  u3=[0.133333333333,0.46666666666]
  for i in range(2,n+1):
    new_z3= (z3[i-1]**3 +z3[i-2]**2)%15
    z3.append(new_z3)
    new_u3=new_z3/15
    u3.append(new_u3)

  x=[]
  
  for i in range(0,n):
    new_u=(u1[i]+u2[i]+u3[i])%1
    u.append(new_u)
    x.append(i)

  plt.bar(x, u)
  plt.xlabel("Iteration") 
  plt.ylabel("Random Number") 
  plt.show()

print(u)